<a href="https://colab.research.google.com/github/miranda15104/THC/blob/main/19_DE_OCTUBRE_arreglos_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2do elemento de la 1er Fila: ', arr[0, 1])


2do elemento de la 1er Fila:  2


In [38]:
#suma de elementos de una matriz lista
suma=0.0
n=[[1,1,1],[1,1,1],[1,1,1]]

for i in range(len(n)):
  for j in range(len(n)):
    suma=suma+n[i][j]
print("suma de la matriz", suma)

suma de la matriz 9.0


In [20]:
#suma de elementos de una matriz 2
A=[1,1,1]
B=[1,1,1]
C=[1,1,1]
print(sum(A)+sum(B)+sum(C))

9


In [28]:
#matriz numpy
import numpy as np
arr = np.array([[1,1,1], [1,1,1], [1,1,1]])
s = np.sum(arr)
print(s)


9


In [32]:
#matriz numpy 2
import numpy as np
arr = np.array([[1,1,1], [1,1,1], [1,1,1]])
for i in range(len(arr)):
#s = np.sum(arr)
 s=((arr[i]+arr[i]+arr[i]))
 print(s+s+s)

[9 9 9]
[9 9 9]
[9 9 9]


In [6]:
a=[[1,1,1],[1,1,1],[1,1,1]]
b=[[1,1,1],[1,1,1],[1,1,1]]
def Productopunto(a,b):
  pp=0.0
  for i in range(len(a)):
    pp=pp+a[i]*b[i]
  return pp

 print(pp)

IndentationError: ignored