<a href="https://colab.research.google.com/github/miranda15104/THC/blob/main/clase_24_de_octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/seismomat/HerramientasComputacionales/blob/main/NivelIntermedio/Modulos_Y_Bibliotecas/Numpy.ipynb

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr [0:4])
print(arr [1:6])
print(arr [1:])
print(arr [0:])
print(arr [:4])
print(arr[-3:-1])  #no toma el segundo
print(arr[-1:])

[2 3 4 5]
[1 2 3 4]
[2 3 4 5 6]
[2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 2 3 4]
[5 6]
[7]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[1:5:2])  #arreglo[inicio:fin:paso]
print(arr[::3])
print(arr[0::])
print(arr[:0:])

[2 4]
[ 1  4  7 10]
[ 1  2  3  4  5  6  7  8  9 10]
[]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[1, :])
print(arr[0:2,2])
print(arr[0:1,2])   #primero renglones #segunda columnas
print(arr[0:2,3])
print(arr[0,3]) #siempre la veo con los santos una m4 y un lambo

[7 8 9]
[ 6  7  8  9 10]
[3 8]
[3]
[4 9]
4


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])
print(arr[0:1, 2:6])

[[2 3 4]
 [7 8 9]]
[[3 4 5]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6]),)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) #********.

x = np.where(arr %2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
import numpy as np  #***************
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.searchsorted(arr, 7, side='right')

print(x)

7


In [ ]:
import numpy as np
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
import numpy as np
arr = np.array([41, 42, 43, 44])

filter_arr = arr %2 ==0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]


In [ ]:
import numpy as np  #suma
x=np.array([1,2,3])
y=np.array([4,5,6])
suma=x+y
resta=x-y
multiplicacion=x*y
divi=x/y

print(f"la suma {suma}")
print(f"la resta {resta}")
print(f"la multiplicación {multiplicacion}")
print(f"la divisición {divi}")

la suma [5 7 9]
la resta [-3 -3 -3]
la multiplicación [ 4 10 18]
la divisición [0.25 0.4  0.5 ]


In [ ]:
import numpy as np  #pi
print(f"Numero pi { np.pi}")

Numero pi 3.141592653589793


In [ ]:
import numpy as np
angulos=np.array([0,np.pi/2, np.pi])
seno=np.sin(angulos)
print(f"los senos {seno}")
print(f"De los angulos {angulos}")

los senos [0.0000000e+00 1.0000000e+00 1.2246468e-16]
De los angulos [0.         1.57079633 3.14159265]


In [ ]:
import numpy as np
angulos=np.array([0,np.pi/2, np.pi])
coseno=np.cos(angulos)
print(f"los senos {coseno}")
print(f"De los angulos {angulos}")

los senos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
De los angulos [0.         1.57079633 3.14159265]


In [ ]:
import numpy as np
x=np.array(list(range(1,9)))
print(x)
matriz= x.reshape(4,2).shape
matriz



[1 2 3 4 5 6 7 8]


(4, 2)

In [ ]:
np.random.uniform(0,1,6)


array([0.08055362, 0.08901275, 0.01709537, 0.14048754, 0.18043166,
       0.47330357])

In [ ]:
np.random.uniform(0,1,size=1)

array([0.7130579])

In [ ]:
x=np.linspace(1,2,4)

In [ ]:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[0:])
x=int(input("escogue un numero de la lista anterior "))
i=0
while i < 4:
  y=np.random.randint(1,10, size=1)
  print("¿este es tu numero?", y)
  i+=1
if i==x:
  print("este es tu numero")



[ 1  2  3  4  5  6  7  8  9 10]
escogue un numero de la lista anterior 3
¿este es tu numero? [5]
¿este es tu numero? [1]
¿este es tu numero? [1]
¿este es tu numero? [2]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[0:])
NUM=int(input("escogue un numero de la lista anterior "))

for x in arr:
  print(NUM)
  if x == "NUM":
    break



[ 1  2  3  4  5  6  7  8  9 10]
escogue un numero de la lista anterior 4
4
4
4
4
4
4
4
4
4
4
